// ── ADMIN USER ──────────────────────────────────────────────────
const user = {
  initials: "MA",
  firstName: "Maria",
  lastName: "Torres",
  fullName: "Maria A. Torres",
  role: "Administrator",
  market: "Pili Public Market",
};

// ── STALL DATA ───────────────────────────────────────────────────
// All stalls for the admin map view.
// posted:true  = publicly posted for vendor application
const stalls = {
  /* ══ GROUND FLOOR — Eatery ══ */
  "GF-EA-1": {
    num: "1",
    floor: "GF",
    section: "Eatery",
    type: "Eatery",
    vendor: "Mang Jose Eatery",
    vendorId: "VND-021",
    rate: 800,
    status: "paid",
    lastPaid: "Mar 5, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#f59e0b,#ef4444",
    init: "MJ",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [
      {
        month: "Mar 2026",
        date: "Mar 5",
        amount: 800,
        method: "Cash",
        or: "OR-2026-0831",
      },
    ],
  },
  "GF-EA-2": {
    num: "2",
    floor: "GF",
    section: "Eatery",
    type: "Eatery",
    vendor: "Nanay Linda",
    vendorId: "VND-022",
    rate: 800,
    status: "paid",
    lastPaid: "Mar 4, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#ec4899,#f97316",
    init: "NL",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [
      {
        month: "Mar 2026",
        date: "Mar 4",
        amount: 800,
        method: "Cash",
        or: "OR-2026-0828",
      },
    ],
  },
  "GF-EA-3": {
    num: "3",
    floor: "GF",
    section: "Eatery",
    type: "Eatery",
    vendor: "Carinderia ni Rosa",
    vendorId: "VND-023",
    rate: 800,
    status: "paid",
    lastPaid: "Mar 6, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#10b981,#0891b2",
    init: "CR",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [
      {
        month: "Mar 2026",
        date: "Mar 6",
        amount: 800,
        method: "Cash",
        or: "OR-2026-0835",
      },
    ],
  },
  "GF-EA-4": {
    num: "4",
    floor: "GF",
    section: "Eatery",
    type: "Eatery",
    vendor: "Pedro Carinderia",
    vendorId: "VND-024",
    rate: 800,
    status: "overdue",
    lastPaid: "Jan 10, 2026",
    balance: 1600,
    overdueDays: 45,
    grad: "135deg,#f59e0b,#ef4444",
    init: "PC",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [
      {
        month: "Jan 2026",
        date: "Jan 10",
        amount: 800,
        method: "Cash",
        or: "OR-2026-0588",
      },
    ],
  },
  "GF-EA-5": {
    num: "5",
    floor: "GF",
    section: "Eatery",
    type: "Eatery",
    vendor: "Lutong Bahay",
    vendorId: "VND-025",
    rate: 800,
    status: "paid",
    lastPaid: "Mar 5, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#14b8a6,#3b82f6",
    init: "LB",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [
      {
        month: "Mar 2026",
        date: "Mar 5",
        amount: 800,
        method: "GCash",
        or: "OR-2026-0830",
      },
    ],
  },
  "GF-EA-6": {
    num: "6",
    floor: "GF",
    section: "Eatery",
    type: "Eatery",
    vendor: "",
    vendorId: "",
    rate: 800,
    status: "vacant",
    lastPaid: "--",
    balance: 0,
    overdueDays: 0,
    grad: "",
    init: "",
    contractExp: "",
    posted: false,
    history: [],
  },
  "GF-EA-7": {
    num: "7",
    floor: "GF",
    section: "Eatery",
    type: "Eatery",
    vendor: "Cris Food Hub",
    vendorId: "VND-026",
    rate: 800,
    status: "partial",
    lastPaid: "Mar 2, 2026",
    balance: 400,
    overdueDays: 0,
    grad: "135deg,#8b5cf6,#6366f1",
    init: "CF",
    contractExp: "Jun 30, 2026",
    posted: false,
    history: [
      {
        month: "Mar 2026",
        date: "Mar 2",
        amount: 400,
        method: "GCash",
        or: "OR-2026-0821",
      },
    ],
  },
  "GF-EA-8": {
    num: "8",
    floor: "GF",
    section: "Eatery",
    type: "Eatery",
    vendor: "Lola Tina",
    vendorId: "VND-027",
    rate: 800,
    status: "paid",
    lastPaid: "Mar 5, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#f97316,#facc15",
    init: "LT",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [
      {
        month: "Mar 2026",
        date: "Mar 5",
        amount: 800,
        method: "Cash",
        or: "OR-2026-0832",
      },
    ],
  },
  "GF-EA-9": {
    num: "9",
    floor: "GF",
    section: "Eatery",
    type: "Eatery",
    vendor: "Manong Ben",
    vendorId: "VND-028",
    rate: 800,
    status: "paid",
    lastPaid: "Mar 4, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#0891b2,#6366f1",
    init: "MB",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [
      {
        month: "Mar 2026",
        date: "Mar 4",
        amount: 800,
        method: "Cash",
        or: "OR-2026-0827",
      },
    ],
  },
  "GF-EA-10": {
    num: "10",
    floor: "GF",
    section: "Eatery",
    type: "Eatery",
    vendor: "Nena Food House",
    vendorId: "VND-029",
    rate: 800,
    status: "paid",
    lastPaid: "Mar 7, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#14b8a6,#6366f1",
    init: "NF",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [
      {
        month: "Mar 2026",
        date: "Mar 7",
        amount: 800,
        method: "Cash",
        or: "OR-2026-0839",
      },
    ],
  },
  /* ══ GROUND FLOOR — RTW ══ */
  "GF-RTW-1": {
    num: "1",
    floor: "GF",
    section: "RTW",
    type: "RTW",
    vendor: "Style Plus",
    vendorId: "VND-030",
    rate: 1000,
    status: "paid",
    lastPaid: "Mar 5, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#0ea5e9,#6366f1",
    init: "SP",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "GF-RTW-2": {
    num: "2",
    floor: "GF",
    section: "RTW",
    type: "RTW",
    vendor: "Dress for Less",
    vendorId: "VND-031",
    rate: 1000,
    status: "paid",
    lastPaid: "Mar 6, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#3b82f6,#6366f1",
    init: "DL",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "GF-RTW-3": {
    num: "3",
    floor: "GF",
    section: "RTW",
    type: "RTW",
    vendor: "Fashionista",
    vendorId: "VND-032",
    rate: 1000,
    status: "paid",
    lastPaid: "Mar 5, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#ec4899,#8b5cf6",
    init: "FS",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "GF-RTW-4": {
    num: "4",
    floor: "GF",
    section: "RTW",
    type: "RTW",
    vendor: "Trendy Threads",
    vendorId: "VND-033",
    rate: 1000,
    status: "paid",
    lastPaid: "Mar 4, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#f59e0b,#ef4444",
    init: "TT",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "GF-RTW-5": {
    num: "5",
    floor: "GF",
    section: "RTW",
    type: "RTW",
    vendor: "",
    vendorId: "",
    rate: 1000,
    status: "vacant",
    lastPaid: "--",
    balance: 0,
    overdueDays: 0,
    grad: "",
    init: "",
    contractExp: "",
    posted: true,
    history: [],
  },
  "GF-RTW-6": {
    num: "6",
    floor: "GF",
    section: "RTW",
    type: "RTW",
    vendor: "Bata Fashion",
    vendorId: "VND-034",
    rate: 1000,
    status: "paid",
    lastPaid: "Mar 5, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#14b8a6,#0891b2",
    init: "BF",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "GF-RTW-7": {
    num: "7",
    floor: "GF",
    section: "RTW",
    type: "RTW",
    vendor: "Tops n More",
    vendorId: "VND-035",
    rate: 1000,
    status: "paid",
    lastPaid: "Mar 6, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#8b5cf6,#d946ef",
    init: "TM",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "GF-RTW-13": {
    num: "13",
    floor: "GF",
    section: "RTW",
    type: "RTW",
    vendor: "Ganda Clothes",
    vendorId: "VND-036",
    rate: 1000,
    status: "overdue",
    lastPaid: "Feb 1, 2026",
    balance: 2000,
    overdueDays: 30,
    grad: "135deg,#ef4444,#f97316",
    init: "GC",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "GF-RTW-14": {
    num: "14",
    floor: "GF",
    section: "RTW",
    type: "RTW",
    vendor: "Lucky Wear",
    vendorId: "VND-037",
    rate: 1000,
    status: "paid",
    lastPaid: "Mar 5, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#f59e0b,#10b981",
    init: "LW",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "GF-RTW-15": {
    num: "15",
    floor: "GF",
    section: "RTW",
    type: "RTW",
    vendor: "Comfort Zone",
    vendorId: "VND-038",
    rate: 1000,
    status: "paid",
    lastPaid: "Mar 4, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#0891b2,#3b82f6",
    init: "CZ",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "GF-RTW-16": {
    num: "16",
    floor: "GF",
    section: "RTW",
    type: "RTW",
    vendor: "Bella Boutique",
    vendorId: "VND-039",
    rate: 1000,
    status: "paid",
    lastPaid: "Mar 6, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#ec4899,#f97316",
    init: "BB",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "GF-RTW-17": {
    num: "17",
    floor: "GF",
    section: "RTW",
    type: "RTW",
    vendor: "",
    vendorId: "",
    rate: 1000,
    status: "vacant",
    lastPaid: "--",
    balance: 0,
    overdueDays: 0,
    grad: "",
    init: "",
    contractExp: "",
    posted: false,
    history: [],
  },
  "GF-RTW-18": {
    num: "18",
    floor: "GF",
    section: "RTW",
    type: "RTW",
    vendor: "Hip Street",
    vendorId: "VND-040",
    rate: 1000,
    status: "paid",
    lastPaid: "Mar 5, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#8b5cf6,#3b82f6",
    init: "HS",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "GF-RTW-19": {
    num: "19",
    floor: "GF",
    section: "RTW",
    type: "RTW",
    vendor: "Moderno",
    vendorId: "VND-041",
    rate: 1000,
    status: "paid",
    lastPaid: "Mar 6, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#14b8a6,#6366f1",
    init: "MO",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  /* ══ GROUND FLOOR — Service ══ */
  "GF-SV-1": {
    num: "1",
    floor: "GF",
    section: "Service",
    type: "Service",
    vendor: "Repair Shop",
    vendorId: "VND-042",
    rate: 700,
    status: "paid",
    lastPaid: "Mar 5, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#10b981,#0891b2",
    init: "RS",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "GF-SV-2": {
    num: "2",
    floor: "GF",
    section: "Service",
    type: "Service",
    vendor: "Watch Repair",
    vendorId: "VND-043",
    rate: 700,
    status: "paid",
    lastPaid: "Mar 4, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#f59e0b,#f97316",
    init: "WR",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "GF-SV-3": {
    num: "3",
    floor: "GF",
    section: "Service",
    type: "Service",
    vendor: "Printing Hub",
    vendorId: "VND-044",
    rate: 700,
    status: "paid",
    lastPaid: "Mar 5, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#3b82f6,#0891b2",
    init: "PH",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "GF-SV-4": {
    num: "4",
    floor: "GF",
    section: "Service",
    type: "Service",
    vendor: "",
    vendorId: "",
    rate: 700,
    status: "vacant",
    lastPaid: "--",
    balance: 0,
    overdueDays: 0,
    grad: "",
    init: "",
    contractExp: "",
    posted: true,
    history: [],
  },
  "GF-SV-5": {
    num: "5",
    floor: "GF",
    section: "Service",
    type: "Service",
    vendor: "Cellphone Shop",
    vendorId: "VND-045",
    rate: 700,
    status: "paid",
    lastPaid: "Mar 6, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#8b5cf6,#3b82f6",
    init: "CS",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "GF-SV-6": {
    num: "6",
    floor: "GF",
    section: "Service",
    type: "Service",
    vendor: "Juan Loading",
    vendorId: "VND-046",
    rate: 700,
    status: "paid",
    lastPaid: "Mar 8, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#3b82f6,#8b5cf6",
    init: "JL",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "GF-SV-7": {
    num: "7",
    floor: "GF",
    section: "Service",
    type: "Service",
    vendor: "Pharmacy",
    vendorId: "VND-047",
    rate: 700,
    status: "paid",
    lastPaid: "Mar 5, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#10b981,#14b8a6",
    init: "PH",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "GF-SV-8": {
    num: "8",
    floor: "GF",
    section: "Service",
    type: "Service",
    vendor: "Barber Shop",
    vendorId: "VND-048",
    rate: 700,
    status: "paid",
    lastPaid: "Mar 4, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#0891b2,#6366f1",
    init: "BS",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  /* ══ GROUND FLOOR — Misc/Pasalubong ══ */
  "GF-MISC-1": {
    num: "1",
    floor: "GF",
    section: "Misc",
    type: "Pasalubong",
    vendor: "Pasalubong ni Ate",
    vendorId: "VND-049",
    rate: 600,
    status: "paid",
    lastPaid: "Mar 7, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#ec4899,#8b5cf6",
    init: "PA",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "GF-MISC-2": {
    num: "2",
    floor: "GF",
    section: "Misc",
    type: "Pasalubong",
    vendor: "Tipid Store",
    vendorId: "VND-050",
    rate: 600,
    status: "paid",
    lastPaid: "Mar 5, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#f59e0b,#ef4444",
    init: "TS",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "GF-MISC-3": {
    num: "3",
    floor: "GF",
    section: "Misc",
    type: "Pasalubong",
    vendor: "Ukay Corner",
    vendorId: "VND-051",
    rate: 600,
    status: "paid",
    lastPaid: "Mar 6, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#10b981,#0891b2",
    init: "UC",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "GF-MISC-4": {
    num: "4",
    floor: "GF",
    section: "Misc",
    type: "Pasalubong",
    vendor: "",
    vendorId: "",
    rate: 600,
    status: "vacant",
    lastPaid: "--",
    balance: 0,
    overdueDays: 0,
    grad: "",
    init: "",
    contractExp: "",
    posted: false,
    history: [],
  },
  "GF-MISC-5": {
    num: "5",
    floor: "GF",
    section: "Misc",
    type: "Pasalubong",
    vendor: "Souvenir Stall",
    vendorId: "VND-052",
    rate: 600,
    status: "paid",
    lastPaid: "Mar 5, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#8b5cf6,#d946ef",
    init: "SS",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "GF-MISC-6": {
    num: "6",
    floor: "GF",
    section: "Misc",
    type: "Pasalubong",
    vendor: "Crisanto Gifts",
    vendorId: "VND-053",
    rate: 600,
    status: "partial",
    lastPaid: "Mar 1, 2026",
    balance: 300,
    overdueDays: 0,
    grad: "135deg,#f59e0b,#10b981",
    init: "CG",
    contractExp: "Jun 30, 2026",
    posted: false,
    history: [],
  },
  "GF-MISC-7": {
    num: "7",
    floor: "GF",
    section: "Misc",
    type: "Pasalubong",
    vendor: "Native Goods",
    vendorId: "VND-054",
    rate: 600,
    status: "paid",
    lastPaid: "Mar 4, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#0891b2,#10b981",
    init: "NG",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "GF-MISC-8": {
    num: "8",
    floor: "GF",
    section: "Misc",
    type: "Pasalubong",
    vendor: "Buko Pie Stall",
    vendorId: "VND-055",
    rate: 600,
    status: "paid",
    lastPaid: "Mar 6, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#14b8a6,#f59e0b",
    init: "BP",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  /* ══ GROUND FLOOR — Footwear ══ */
  "GF-FW-1": {
    num: "1",
    floor: "GF",
    section: "Footwear",
    type: "Footwear",
    vendor: "Sapatos Depot",
    vendorId: "VND-056",
    rate: 900,
    status: "paid",
    lastPaid: "Mar 5, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#9333ea,#6366f1",
    init: "SD",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "GF-FW-2": {
    num: "2",
    floor: "GF",
    section: "Footwear",
    type: "Footwear",
    vendor: "Step In",
    vendorId: "VND-057",
    rate: 900,
    status: "paid",
    lastPaid: "Mar 6, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#7c3aed,#9333ea",
    init: "SI",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "GF-FW-3": {
    num: "3",
    floor: "GF",
    section: "Footwear",
    type: "Footwear",
    vendor: "Shoe World",
    vendorId: "VND-058",
    rate: 900,
    status: "paid",
    lastPaid: "Mar 5, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#6366f1,#8b5cf6",
    init: "SW",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "GF-FW-4": {
    num: "4",
    floor: "GF",
    section: "Footwear",
    type: "Footwear",
    vendor: "",
    vendorId: "",
    rate: 900,
    status: "vacant",
    lastPaid: "--",
    balance: 0,
    overdueDays: 0,
    grad: "",
    init: "",
    contractExp: "",
    posted: false,
    history: [],
  },
  "GF-FW-5": {
    num: "5",
    floor: "GF",
    section: "Footwear",
    type: "Footwear",
    vendor: "Sole Mates",
    vendorId: "VND-059",
    rate: 900,
    status: "paid",
    lastPaid: "Mar 4, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#a855f7,#7c3aed",
    init: "SM",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "GF-FW-6": {
    num: "6",
    floor: "GF",
    section: "Footwear",
    type: "Footwear",
    vendor: "Comfort Toes",
    vendorId: "VND-059b",
    rate: 900,
    status: "paid",
    lastPaid: "Mar 6, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#8b5cf6,#6366f1",
    init: "CT",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "GF-FW-7": {
    num: "7",
    floor: "GF",
    section: "Footwear",
    type: "Footwear",
    vendor: "Suot na Sapatos",
    vendorId: "VND-059c",
    rate: 900,
    status: "partial",
    lastPaid: "Mar 2, 2026",
    balance: 450,
    overdueDays: 0,
    grad: "135deg,#d946ef,#9333ea",
    init: "SS",
    contractExp: "Jun 30, 2026",
    posted: false,
    history: [],
  },
  "GF-FW-8": {
    num: "8",
    floor: "GF",
    section: "Footwear",
    type: "Footwear",
    vendor: "",
    vendorId: "",
    rate: 900,
    status: "vacant",
    lastPaid: "--",
    balance: 0,
    overdueDays: 0,
    grad: "",
    init: "",
    contractExp: "",
    posted: false,
    history: [],
  },
  /* ══ SECOND FLOOR — Ukay-Ukay ══ */
  "SF-UK-1": {
    num: "1",
    floor: "SF",
    section: "Ukay",
    type: "Ukay-Ukay",
    vendor: "Ukay Masters",
    vendorId: "VND-060",
    rate: 700,
    status: "paid",
    lastPaid: "Mar 5, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#f59e0b,#10b981",
    init: "UM",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-UK-2": {
    num: "2",
    floor: "SF",
    section: "Ukay",
    type: "Ukay-Ukay",
    vendor: "Second Chance",
    vendorId: "VND-061",
    rate: 700,
    status: "paid",
    lastPaid: "Mar 6, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#0891b2,#3b82f6",
    init: "SC",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-UK-3": {
    num: "3",
    floor: "SF",
    section: "Ukay",
    type: "Ukay-Ukay",
    vendor: "Budget Fashion",
    vendorId: "VND-062",
    rate: 700,
    status: "paid",
    lastPaid: "Mar 5, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#ec4899,#8b5cf6",
    init: "BF",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-UK-4": {
    num: "4",
    floor: "SF",
    section: "Ukay",
    type: "Ukay-Ukay",
    vendor: "",
    vendorId: "",
    rate: 700,
    status: "vacant",
    lastPaid: "--",
    balance: 0,
    overdueDays: 0,
    grad: "",
    init: "",
    contractExp: "",
    posted: false,
    history: [],
  },
  "SF-UK-5": {
    num: "5",
    floor: "SF",
    section: "Ukay",
    type: "Ukay-Ukay",
    vendor: "Preloved Plus",
    vendorId: "VND-062b",
    rate: 700,
    status: "paid",
    lastPaid: "Mar 5, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#8b5cf6,#ec4899",
    init: "PP",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-UK-6": {
    num: "6",
    floor: "SF",
    section: "Ukay",
    type: "Ukay-Ukay",
    vendor: "Thrift King",
    vendorId: "VND-062c",
    rate: 700,
    status: "paid",
    lastPaid: "Mar 6, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#f97316,#f59e0b",
    init: "TK",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-UK-7": {
    num: "7",
    floor: "SF",
    section: "Ukay",
    type: "Ukay-Ukay",
    vendor: "",
    vendorId: "",
    rate: 700,
    status: "vacant",
    lastPaid: "--",
    balance: 0,
    overdueDays: 0,
    grad: "",
    init: "",
    contractExp: "",
    posted: false,
    history: [],
  },
  "SF-UK-8": {
    num: "8",
    floor: "SF",
    section: "Ukay",
    type: "Ukay-Ukay",
    vendor: "Kwenta Clothes",
    vendorId: "VND-062d",
    rate: 700,
    status: "paid",
    lastPaid: "Mar 4, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#14b8a6,#6366f1",
    init: "KC",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-UK-9": {
    num: "9",
    floor: "SF",
    section: "Ukay",
    type: "Ukay-Ukay",
    vendor: "Class A Ukay",
    vendorId: "VND-063",
    rate: 700,
    status: "overdue",
    lastPaid: "Jan 15, 2026",
    balance: 1400,
    overdueDays: 32,
    grad: "135deg,#ef4444,#f97316",
    init: "CA",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-UK-10": {
    num: "10",
    floor: "SF",
    section: "Ukay",
    type: "Ukay-Ukay",
    vendor: "Ref.Clothes",
    vendorId: "VND-064",
    rate: 700,
    status: "paid",
    lastPaid: "Mar 5, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#f59e0b,#f97316",
    init: "RC",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-UK-11": {
    num: "11",
    floor: "SF",
    section: "Ukay",
    type: "Ukay-Ukay",
    vendor: "Bale Style",
    vendorId: "VND-064b",
    rate: 700,
    status: "paid",
    lastPaid: "Mar 6, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#0891b2,#14b8a6",
    init: "BS",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-UK-12": {
    num: "12",
    floor: "SF",
    section: "Ukay",
    type: "Ukay-Ukay",
    vendor: "",
    vendorId: "",
    rate: 700,
    status: "vacant",
    lastPaid: "--",
    balance: 0,
    overdueDays: 0,
    grad: "",
    init: "",
    contractExp: "",
    posted: false,
    history: [],
  },
  "SF-UK-13": {
    num: "13",
    floor: "SF",
    section: "Ukay",
    type: "Ukay-Ukay",
    vendor: "Sulit Threads",
    vendorId: "VND-064c",
    rate: 700,
    status: "paid",
    lastPaid: "Mar 5, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#6366f1,#8b5cf6",
    init: "ST",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-UK-14": {
    num: "14",
    floor: "SF",
    section: "Ukay",
    type: "Ukay-Ukay",
    vendor: "Bargain Hub",
    vendorId: "VND-064d",
    rate: 700,
    status: "paid",
    lastPaid: "Mar 4, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#f97316,#ef4444",
    init: "BH",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-UK-15": {
    num: "15",
    floor: "SF",
    section: "Ukay",
    type: "Ukay-Ukay",
    vendor: "",
    vendorId: "",
    rate: 700,
    status: "vacant",
    lastPaid: "--",
    balance: 0,
    overdueDays: 0,
    grad: "",
    init: "",
    contractExp: "",
    posted: false,
    history: [],
  },
  "SF-UK-16": {
    num: "16",
    floor: "SF",
    section: "Ukay",
    type: "Ukay-Ukay",
    vendor: "Old is Gold",
    vendorId: "VND-064e",
    rate: 700,
    status: "paid",
    lastPaid: "Mar 5, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#ca8a04,#f59e0b",
    init: "OG",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-UK-17": {
    num: "17",
    floor: "SF",
    section: "Ukay",
    type: "Ukay-Ukay",
    vendor: "Style for Less",
    vendorId: "VND-064f",
    rate: 700,
    status: "paid",
    lastPaid: "Mar 6, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#8b5cf6,#d946ef",
    init: "SL",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-UK-18": {
    num: "18",
    floor: "SF",
    section: "Ukay",
    type: "Ukay-Ukay",
    vendor: "Lucky Find",
    vendorId: "VND-064g",
    rate: 700,
    status: "partial",
    lastPaid: "Mar 3, 2026",
    balance: 350,
    overdueDays: 0,
    grad: "135deg,#3b82f6,#6366f1",
    init: "LF",
    contractExp: "Jun 30, 2026",
    posted: false,
    history: [],
  },
  "SF-UK-19": {
    num: "19",
    floor: "SF",
    section: "Ukay",
    type: "Ukay-Ukay",
    vendor: "Bale Clothes",
    vendorId: "VND-065",
    rate: 700,
    status: "paid",
    lastPaid: "Mar 4, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#14b8a6,#0891b2",
    init: "BC",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-UK-20": {
    num: "20",
    floor: "SF",
    section: "Ukay",
    type: "Ukay-Ukay",
    vendor: "",
    vendorId: "",
    rate: 700,
    status: "vacant",
    lastPaid: "--",
    balance: 0,
    overdueDays: 0,
    grad: "",
    init: "",
    contractExp: "",
    posted: true,
    history: [],
  },
  "SF-UK-21": {
    num: "21",
    floor: "SF",
    section: "Ukay",
    type: "Ukay-Ukay",
    vendor: "Tipid Fashion",
    vendorId: "VND-065b",
    rate: 700,
    status: "paid",
    lastPaid: "Mar 5, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#f59e0b,#ec4899",
    init: "TF",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-UK-22": {
    num: "22",
    floor: "SF",
    section: "Ukay",
    type: "Ukay-Ukay",
    vendor: "",
    vendorId: "",
    rate: 700,
    status: "vacant",
    lastPaid: "--",
    balance: 0,
    overdueDays: 0,
    grad: "",
    init: "",
    contractExp: "",
    posted: false,
    history: [],
  },
  "SF-UK-23": {
    num: "23",
    floor: "SF",
    section: "Ukay",
    type: "Ukay-Ukay",
    vendor: "Budget Bazaar",
    vendorId: "VND-065c",
    rate: 700,
    status: "paid",
    lastPaid: "Mar 6, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#0891b2,#3b82f6",
    init: "BB",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-UK-24": {
    num: "24",
    floor: "SF",
    section: "Ukay",
    type: "Ukay-Ukay",
    vendor: "",
    vendorId: "",
    rate: 700,
    status: "vacant",
    lastPaid: "--",
    balance: 0,
    overdueDays: 0,
    grad: "",
    init: "",
    contractExp: "",
    posted: false,
    history: [],
  },
  "SF-UK-25": {
    num: "25",
    floor: "SF",
    section: "Ukay",
    type: "Ukay-Ukay",
    vendor: "Panday Style",
    vendorId: "VND-065d",
    rate: 700,
    status: "paid",
    lastPaid: "Mar 5, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#6366f1,#8b5cf6",
    init: "PS",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  /* ══ SECOND FLOOR — Special Purpose ══ */
  "SF-SP-5": {
    num: "5",
    floor: "SF",
    section: "Special",
    type: "Special Purpose",
    vendor: "Market Admin Office",
    vendorId: "VND-SP1",
    rate: 0,
    status: "paid",
    lastPaid: "--",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#0ea5e9,#0369a1",
    init: "MA",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-SP-6": {
    num: "6",
    floor: "SF",
    section: "Special",
    type: "Special Purpose",
    vendor: "",
    vendorId: "",
    rate: 1200,
    status: "vacant",
    lastPaid: "--",
    balance: 0,
    overdueDays: 0,
    grad: "",
    init: "",
    contractExp: "",
    posted: false,
    history: [],
  },
  "SF-SP-7": {
    num: "7",
    floor: "SF",
    section: "Special",
    type: "Special Purpose",
    vendor: "Storage Room",
    vendorId: "VND-SP2",
    rate: 0,
    status: "paid",
    lastPaid: "--",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#64748b,#94a3b8",
    init: "SR",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-SP-8": {
    num: "8",
    floor: "SF",
    section: "Special",
    type: "Special Purpose",
    vendor: "",
    vendorId: "",
    rate: 1200,
    status: "vacant",
    lastPaid: "--",
    balance: 0,
    overdueDays: 0,
    grad: "",
    init: "",
    contractExp: "",
    posted: false,
    history: [],
  },
  /* ══ SECOND FLOOR — Vegetable ══ */
  "SF-VG-1": {
    num: "1",
    floor: "SF",
    section: "Veggie",
    type: "Vegetables",
    vendor: "Tindahan ni Maria",
    vendorId: "VND-070",
    rate: 900,
    status: "paid",
    lastPaid: "Mar 8, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#10b981,#0891b2",
    init: "TM",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-VG-2": {
    num: "2",
    floor: "SF",
    section: "Veggie",
    type: "Vegetables",
    vendor: "Gulay Express",
    vendorId: "VND-071",
    rate: 900,
    status: "paid",
    lastPaid: "Mar 7, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#16a34a,#14b8a6",
    init: "GE",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-VG-3": {
    num: "3",
    floor: "SF",
    section: "Veggie",
    type: "Vegetables",
    vendor: "Sariling Gulay",
    vendorId: "VND-071b",
    rate: 900,
    status: "paid",
    lastPaid: "Mar 6, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#22c55e,#10b981",
    init: "SG",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-VG-4": {
    num: "4",
    floor: "SF",
    section: "Veggie",
    type: "Vegetables",
    vendor: "Green Corner",
    vendorId: "VND-071c",
    rate: 900,
    status: "paid",
    lastPaid: "Mar 5, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#14b8a6,#16a34a",
    init: "GC",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-VG-5": {
    num: "5",
    floor: "SF",
    section: "Veggie",
    type: "Vegetables",
    vendor: "Luntiang Tindahan",
    vendorId: "VND-071d",
    rate: 900,
    status: "paid",
    lastPaid: "Mar 4, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#16a34a,#22c55e",
    init: "LT",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-VG-6": {
    num: "6",
    floor: "SF",
    section: "Veggie",
    type: "Vegetables",
    vendor: "",
    vendorId: "",
    rate: 900,
    status: "vacant",
    lastPaid: "--",
    balance: 0,
    overdueDays: 0,
    grad: "",
    init: "",
    contractExp: "",
    posted: false,
    history: [],
  },
  "SF-VG-7": {
    num: "7",
    floor: "SF",
    section: "Veggie",
    type: "Vegetables",
    vendor: "Organiko",
    vendorId: "VND-071e",
    rate: 900,
    status: "paid",
    lastPaid: "Mar 5, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#10b981,#16a34a",
    init: "OR",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-VG-8": {
    num: "8",
    floor: "SF",
    section: "Veggie",
    type: "Vegetables",
    vendor: "Farm2Table",
    vendorId: "VND-071f",
    rate: 900,
    status: "paid",
    lastPaid: "Mar 6, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#22c55e,#14b8a6",
    init: "FT",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-VG-9": {
    num: "9",
    floor: "SF",
    section: "Veggie",
    type: "Vegetables",
    vendor: "",
    vendorId: "",
    rate: 900,
    status: "vacant",
    lastPaid: "--",
    balance: 0,
    overdueDays: 0,
    grad: "",
    init: "",
    contractExp: "",
    posted: false,
    history: [],
  },
  "SF-VG-10": {
    num: "10",
    floor: "SF",
    section: "Veggie",
    type: "Vegetables",
    vendor: "Pedro Gulay",
    vendorId: "VND-072",
    rate: 900,
    status: "partial",
    lastPaid: "Mar 3, 2026",
    balance: 450,
    overdueDays: 0,
    grad: "135deg,#8b5cf6,#6366f1",
    init: "PG",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-VG-11": {
    num: "11",
    floor: "SF",
    section: "Veggie",
    type: "Vegetables",
    vendor: "Sitaw World",
    vendorId: "VND-072b",
    rate: 900,
    status: "paid",
    lastPaid: "Mar 5, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#16a34a,#10b981",
    init: "SW",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-VG-12": {
    num: "12",
    floor: "SF",
    section: "Veggie",
    type: "Vegetables",
    vendor: "Pechay Palace",
    vendorId: "VND-072c",
    rate: 900,
    status: "paid",
    lastPaid: "Mar 4, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#22c55e,#16a34a",
    init: "PP",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-VG-13": {
    num: "13",
    floor: "SF",
    section: "Veggie",
    type: "Vegetables",
    vendor: "Kangkong Hub",
    vendorId: "VND-072d",
    rate: 900,
    status: "paid",
    lastPaid: "Mar 6, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#14b8a6,#22c55e",
    init: "KH",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-VG-14": {
    num: "14",
    floor: "SF",
    section: "Veggie",
    type: "Vegetables",
    vendor: "",
    vendorId: "",
    rate: 900,
    status: "vacant",
    lastPaid: "--",
    balance: 0,
    overdueDays: 0,
    grad: "",
    init: "",
    contractExp: "",
    posted: false,
    history: [],
  },
  "SF-VG-15": {
    num: "15",
    floor: "SF",
    section: "Veggie",
    type: "Vegetables",
    vendor: "Luya Central",
    vendorId: "VND-072e",
    rate: 900,
    status: "paid",
    lastPaid: "Mar 5, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#10b981,#0891b2",
    init: "LC",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-VG-16": {
    num: "16",
    floor: "SF",
    section: "Veggie",
    type: "Vegetables",
    vendor: "Bawang Central",
    vendorId: "VND-072f",
    rate: 900,
    status: "paid",
    lastPaid: "Mar 4, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#16a34a,#14b8a6",
    init: "BC",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-VG-17": {
    num: "17",
    floor: "SF",
    section: "Veggie",
    type: "Vegetables",
    vendor: "Fresh Veggies",
    vendorId: "VND-073",
    rate: 900,
    status: "paid",
    lastPaid: "Mar 5, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#10b981,#16a34a",
    init: "FV",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-VG-18": {
    num: "18",
    floor: "SF",
    section: "Veggie",
    type: "Vegetables",
    vendor: "",
    vendorId: "",
    rate: 900,
    status: "vacant",
    lastPaid: "--",
    balance: 0,
    overdueDays: 0,
    grad: "",
    init: "",
    contractExp: "",
    posted: false,
    history: [],
  },
  /* ══ SECOND FLOOR — Fruit ══ */
  "SF-FR-1": {
    num: "1",
    floor: "SF",
    section: "Fruit",
    type: "Fruits",
    vendor: "Frutas ni Lola",
    vendorId: "VND-080",
    rate: 850,
    status: "paid",
    lastPaid: "Mar 7, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#22c55e,#10b981",
    init: "FL",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-FR-2": {
    num: "2",
    floor: "SF",
    section: "Fruit",
    type: "Fruits",
    vendor: "Sweet Fruits",
    vendorId: "VND-081",
    rate: 850,
    status: "paid",
    lastPaid: "Mar 6, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#22c55e,#14b8a6",
    init: "SF",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-FR-3": {
    num: "3",
    floor: "SF",
    section: "Fruit",
    type: "Fruits",
    vendor: "Mango Queen",
    vendorId: "VND-081b",
    rate: 850,
    status: "paid",
    lastPaid: "Mar 5, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#f59e0b,#f97316",
    init: "MQ",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-FR-4": {
    num: "4",
    floor: "SF",
    section: "Fruit",
    type: "Fruits",
    vendor: "",
    vendorId: "",
    rate: 850,
    status: "vacant",
    lastPaid: "--",
    balance: 0,
    overdueDays: 0,
    grad: "",
    init: "",
    contractExp: "",
    posted: false,
    history: [],
  },
  "SF-FR-5": {
    num: "5",
    floor: "SF",
    section: "Fruit",
    type: "Fruits",
    vendor: "Tropical Harvest",
    vendorId: "VND-082",
    rate: 850,
    status: "overdue",
    lastPaid: "Feb 5, 2026",
    balance: 1700,
    overdueDays: 25,
    grad: "135deg,#f97316,#ef4444",
    init: "TH",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-FR-6": {
    num: "6",
    floor: "SF",
    section: "Fruit",
    type: "Fruits",
    vendor: "Buko Fresh",
    vendorId: "VND-083",
    rate: 850,
    status: "paid",
    lastPaid: "Mar 9, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#14b8a6,#22c55e",
    init: "BF",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-FR-7": {
    num: "7",
    floor: "SF",
    section: "Fruit",
    type: "Fruits",
    vendor: "Citrus Corner",
    vendorId: "VND-083b",
    rate: 850,
    status: "paid",
    lastPaid: "Mar 6, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#f59e0b,#22c55e",
    init: "CC",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-FR-19": {
    num: "19",
    floor: "SF",
    section: "Fruit",
    type: "Fruits",
    vendor: "",
    vendorId: "",
    rate: 850,
    status: "vacant",
    lastPaid: "--",
    balance: 0,
    overdueDays: 0,
    grad: "",
    init: "",
    contractExp: "",
    posted: false,
    history: [],
  },
  "SF-FR-20": {
    num: "20",
    floor: "SF",
    section: "Fruit",
    type: "Fruits",
    vendor: "Pinya House",
    vendorId: "VND-083c",
    rate: 850,
    status: "paid",
    lastPaid: "Mar 5, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#f97316,#f59e0b",
    init: "PH",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-FR-21": {
    num: "21",
    floor: "SF",
    section: "Fruit",
    type: "Fruits",
    vendor: "Papaya Stand",
    vendorId: "VND-083d",
    rate: 850,
    status: "paid",
    lastPaid: "Mar 4, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#f59e0b,#10b981",
    init: "PS",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-FR-22": {
    num: "22",
    floor: "SF",
    section: "Fruit",
    type: "Fruits",
    vendor: "Watermelon Hub",
    vendorId: "VND-083e",
    rate: 850,
    status: "paid",
    lastPaid: "Mar 6, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#ef4444,#f97316",
    init: "WH",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-FR-23": {
    num: "23",
    floor: "SF",
    section: "Fruit",
    type: "Fruits",
    vendor: "Melon World",
    vendorId: "VND-083f",
    rate: 850,
    status: "paid",
    lastPaid: "Mar 5, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#22c55e,#f59e0b",
    init: "MW",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-FR-24": {
    num: "24",
    floor: "SF",
    section: "Fruit",
    type: "Fruits",
    vendor: "",
    vendorId: "",
    rate: 850,
    status: "vacant",
    lastPaid: "--",
    balance: 0,
    overdueDays: 0,
    grad: "",
    init: "",
    contractExp: "",
    posted: false,
    history: [],
  },
  "SF-FR-25": {
    num: "25",
    floor: "SF",
    section: "Fruit",
    type: "Fruits",
    vendor: "Grape Lane",
    vendorId: "VND-083g",
    rate: 850,
    status: "paid",
    lastPaid: "Mar 5, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#8b5cf6,#a855f7",
    init: "GL",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-FR-26": {
    num: "26",
    floor: "SF",
    section: "Fruit",
    type: "Fruits",
    vendor: "Berries Galore",
    vendorId: "VND-083h",
    rate: 850,
    status: "paid",
    lastPaid: "Mar 4, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#ef4444,#8b5cf6",
    init: "BG",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  /* ══ SECOND FLOOR — Egg ══ */
  "SF-EG-1": {
    num: "1",
    floor: "SF",
    section: "Egg",
    type: "Eggs",
    vendor: "Itlog ni Mang Ben",
    vendorId: "VND-090",
    rate: 700,
    status: "paid",
    lastPaid: "Mar 6, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#f59e0b,#f97316",
    init: "IM",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [
      {
        month: "Mar 2026",
        date: "Mar 6",
        amount: 700,
        method: "Cash",
        or: "OR-2026-0834",
      },
    ],
  },
  "SF-EG-2": {
    num: "2",
    floor: "SF",
    section: "Egg",
    type: "Eggs",
    vendor: "Egg World",
    vendorId: "VND-091",
    rate: 700,
    status: "paid",
    lastPaid: "Mar 5, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#f97316,#facc15",
    init: "EW",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-EG-3": {
    num: "3",
    floor: "SF",
    section: "Egg",
    type: "Eggs",
    vendor: "Fresh Eggs",
    vendorId: "VND-091b",
    rate: 700,
    status: "paid",
    lastPaid: "Mar 4, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#f59e0b,#facc15",
    init: "FE",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-EG-4": {
    num: "4",
    floor: "SF",
    section: "Egg",
    type: "Eggs",
    vendor: "",
    vendorId: "",
    rate: 700,
    status: "vacant",
    lastPaid: "--",
    balance: 0,
    overdueDays: 0,
    grad: "",
    init: "",
    contractExp: "",
    posted: false,
    history: [],
  },
  "SF-EG-5": {
    num: "5",
    floor: "SF",
    section: "Egg",
    type: "Eggs",
    vendor: "Poultry Shop",
    vendorId: "VND-091c",
    rate: 700,
    status: "paid",
    lastPaid: "Mar 5, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#facc15,#f59e0b",
    init: "PS",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-EG-6": {
    num: "6",
    floor: "SF",
    section: "Egg",
    type: "Eggs",
    vendor: "Egg Express",
    vendorId: "VND-091d",
    rate: 700,
    status: "paid",
    lastPaid: "Mar 6, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#f97316,#f59e0b",
    init: "EE",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
  "SF-EG-7": {
    num: "7",
    floor: "SF",
    section: "Egg",
    type: "Eggs",
    vendor: "Sunny Side",
    vendorId: "VND-091e",
    rate: 700,
    status: "paid",
    lastPaid: "Mar 4, 2026",
    balance: 0,
    overdueDays: 0,
    grad: "135deg,#facc15,#f97316",
    init: "SS",
    contractExp: "Dec 31, 2026",
    posted: false,
    history: [],
  },
};

// ── LISTING DETAILS (pre-seeded for already-posted stalls) ────────
const stallListings = {
  "GF-RTW-5": {
    imgSrc: "",
    imgColor: "#dbeafe",
    imgAccent: "#1d4ed8",
    description:
      "Well-lit corner stall near the main entrance of the RTW Section. Suitable for clothing, accessories, or fashion retail. High foot traffic daily.",
    size: "3 x 3 m",
    sizeLabel: "9 sq.m.",
    price: 1000,
    postedDate: "Mar 10, 2026",
  },
  "GF-SV-4": {
    imgSrc: "",
    imgColor: "#f0fdf4",
    imgAccent: "#16a34a",
    description:
      "Service section stall near the loading area. Ideal for repair shops, printing, cellphone accessories, or small service businesses.",
    size: "3 x 2 m",
    sizeLabel: "6 sq.m.",
    price: 700,
    postedDate: "Mar 8, 2026",
  },
  "SF-UK-20": {
    imgSrc: "",
    imgColor: "#fef9c3",
    imgAccent: "#ca8a04",
    description:
      "Upper floor ukay-ukay stall with good visibility from the main corridor. Perfect for secondhand apparel, accessories, or vintage items.",
    size: "3 x 3 m",
    sizeLabel: "9 sq.m.",
    price: 700,
    postedDate: "Mar 15, 2026",
  },
};

// ── SUMMARY ───────────────────────────────────────────────────────
function getStallSummary(stallData) {
  const vals = Object.values(stallData);
  return {
    total: vals.length,
    occupied: vals.filter((s) => s.vendor).length,
    vacant: vals.filter((s) => !s.vendor).length,
    overdue: vals.filter((s) => s.status === "overdue").length,
    posted: vals.filter((s) => s.posted).length,
  };
}

// ── CONTROLLER ────────────────────────────────────────────────────
const showStallManagement = (req, res) => {
  const summary = getStallSummary(stalls);
  res.render("admin/stall-management", {
    user,
    stalls,
    stallListings,
    summary,
  });
};

module.exports = { showStallManagement };
