const vendors = [
    {
      id: "VND-001",
      firstName: "Juan",
      lastName: "Dela Cruz",
      initials: "JD",
      stall: "#01",
      type: "Wet Market",
      typeCode: "wet",
      phone: "+63 912 345 6789",
      email: "juan.delacruz@email.com",
      address: "Brgy. Norte, Arkipaisi",
      since: "Mar 9, 2025",
      status: "active",
      contractStart: "Mar 9, 2025",
      contractEnd: "Mar 9, 2026",
      contractProgress: 75,
      progressClass: "warn",
      monthlyRate: "₱1,500",
      balance: "₱0.00",
      lastPayment: "Mar 1, 2026",
      isOnline: true,
    },
    {
      id: "VND-002",
      firstName: "Pedro",
      lastName: "Reyes",
      initials: "PR",
      stall: "#03",
      type: "Meat Section",
      typeCode: "meat",
      phone: "+63 917 111 2222",
      email: "pedro.reyes@email.com",
      address: "Brgy. Silangan, Arkipaisi",
      since: "Jan 5, 2025",
      status: "active",
      contractStart: "Jan 5, 2025",
      contractEnd: "Jan 5, 2026",
      contractProgress: 91,
      progressClass: "crit",
      monthlyRate: "₱1,800",
      balance: "₱500.00",
      lastPayment: "Feb 28, 2026",
      isOnline: false,
    },
    {
      id: "VND-003",
      firstName: "Maria",
      lastName: "Santos",
      initials: "MS",
      stall: "#07",
      type: "Dry Goods",
      typeCode: "dry",
      phone: "+63 920 333 4444",
      email: "maria.santos@email.com",
      address: "Brgy. Doon, Arkipaisi",
      since: "Jun 12, 2024",
      status: "active",
      contractStart: "Jun 12, 2024",
      contractEnd: "Jun 12, 2025",
      contractProgress: 48,
      progressClass: "ok",
      monthlyRate: "₱1,200",
      balance: "₱0.00",
      lastPayment: "Mar 3, 2026",
      isOnline: true,
    },
    {
      id: "VND-004",
      firstName: "Ana",
      lastName: "Lim",
      initials: "AL",
      stall: "#19",
      type: "Vegetables",
      typeCode: "veg",
      phone: "+63 918 555 6666",
      email: "ana.lim@email.com",
      address: "Brgy. Centro, Arkipaisi",
      since: "Sep 20, 2024",
      status: "suspended",
      contractStart: "Sep 20, 2024",
      contractEnd: "Sep 20, 2025",
      contractProgress: 62,
      progressClass: "warn",
      monthlyRate: "₱1,000",
      balance: "₱3,000.00",
      lastPayment: "Jan 15, 2026",
      isOnline: false,
    },
    {
      id: "VND-005",
      firstName: "Roberto",
      lastName: "Go",
      initials: "RG",
      stall: "#24",
      type: "Fish Section",
      typeCode: "fish",
      phone: "+63 915 777 8888",
      email: "roberto.go@email.com",
      address: "Brgy. Likha, Arkipaisi",
      since: "Dec 1, 2023",
      status: "expired",
      contractStart: "Dec 1, 2023",
      contractEnd: "Dec 1, 2024",
      contractProgress: 100,
      progressClass: "ex",
      monthlyRate: "₱2,000",
      balance: "₱1,500.00",
      lastPayment: "Nov 30, 2024",
      isOnline: false,
    },
    {
      id: "VND-006",
      firstName: "Carla",
      lastName: "Bautista",
      initials: "CB",
      stall: "#06",
      type: "Dry Goods",
      typeCode: "dry",
      phone: "+63 912 987 6543",
      email: "carla.bautista@email.com",
      address: "Brgy. Bagong, Arkipaisi",
      since: "Mar 9, 2026",
      status: "active",
      contractStart: "Mar 9, 2026",
      contractEnd: "Mar 9, 2027",
      contractProgress: 2,
      progressClass: "ok",
      monthlyRate: "₱1,200",
      balance: "₱0.00",
      lastPayment: "—",
      isOnline: true,
    },
    {
      id: "VND-007",
      firstName: "Luis",
      lastName: "Villanueva",
      initials: "LV",
      stall: "#11",
      type: "Vegetables",
      typeCode: "veg",
      phone: "+63 917 234 5678",
      email: "luis.v@email.com",
      address: "Brgy. Ibayo, Arkipaisi",
      since: "Feb 1, 2025",
      status: "active",
      contractStart: "Feb 1, 2025",
      contractEnd: "Feb 1, 2026",
      contractProgress: 82,
      progressClass: "warn",
      monthlyRate: "₱1,000",
      balance: "₱0.00",
      lastPayment: "Mar 5, 2026",
      isOnline: false,
    },
    {
      id: "VND-008",
      firstName: "Grace",
      lastName: "Cruz",
      initials: "GC",
      stall: "#09",
      type: "Vegetables",
      typeCode: "veg",
      phone: "+63 918 333 4444",
      email: "grace.c@email.com",
      address: "Brgy. Tulay, Arkipaisi",
      since: "Jul 12, 2024",
      status: "active",
      contractStart: "Jul 12, 2024",
      contractEnd: "Jul 12, 2025",
      contractProgress: 55,
      progressClass: "warn",
      monthlyRate: "₱1,000",
      balance: "₱0.00",
      lastPayment: "Mar 4, 2026",
      isOnline: true,
    },
    {
      id: "VND-009",
      firstName: "Diego",
      lastName: "Cruz",
      initials: "DC",
      stall: "#15",
      type: "General",
      typeCode: "gen",
      phone: "+63 916 444 5555",
      email: "diego.c@email.com",
      address: "Brgy. Luma, Arkipaisi",
      since: "May 15, 2022",
      status: "terminated",
      contractStart: "May 15, 2022",
      contractEnd: "May 15, 2023",
      contractProgress: 100,
      progressClass: "ex",
      monthlyRate: "₱1,200",
      balance: "₱8,500.00",
      lastPayment: "Apr 10, 2023",
      isOnline: false,
    },
  ];
  
  // Derive summary stats from data
  function getStats(vendorList) {
    return {
      total: vendorList.length,
      active: vendorList.filter((v) => v.status === "active").length,
      suspended: vendorList.filter((v) => v.status === "suspended").length,
      expired: vendorList.filter((v) => v.status === "expired").length,
      terminated: vendorList.filter((v) => v.status === "terminated").length,
    };
  }
  
  const showVendorManagement = (req, res) => {
    const stats = getStats(vendors);
    res.render("admin/vendor-management", { vendors, stats });
  };
  
  module.exports = { showVendorManagement };